apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: TimeZoneCalculator
  tags:
    - "cluster:inergank"
    - "contains-pii:false"
    - "tier:1"
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: component
